routes/catagory.py
from flask import Blueprint, render_template, abort,request,flash,redirect,jsonify,url_for
from jinja2 import TemplateNotFound
from flask import session as login_session
import json


from database.entityManagerService import EntityManagerService, CatagoryService, ItemService, UserService
from database.database_set_up import User,Item,Catagory

import requests

catagory_routes = Blueprint('catagory', __name__,
                        template_folder='templates')


# Services for CRUD operations
eMS = EntityManagerService()
userService = UserService()
catagoryService = CatagoryService()
itemService = ItemService()

def isLoggedIn():
    access_token = login_session.get('access_token')
    if access_token is None:
        return False
    else:
        return True


# Default Mapping
@catagory_routes.route('/')
@catagory_routes.route('/catalog/')
def showCatalog():
    categories = catagoryService.getCatagoriesList()
    items = itemService.getItemList()
    isUserLoggedIn = isLoggedIn()
    if isUserLoggedIn == True:
        userName = login_session['username']
        userImage = login_session['picture']
    else:
        userName = ""
        userImage = ""

    return render_template('catagories.html', categories=categories,show_welcome='true', items=items, isLoggedIn=isUserLoggedIn, user_name=userName, user_image=userImage)



# Add a category
@catagory_routes.route('/catalog/addcategory', methods=['GET', 'POST'])
def addCatagory():    

    # Validate if current user is logged in
    if isLoggedIn():
        if request.method == 'POST':
            user = userService.getUserByNameAndId(login_session['username'],login_session['email'])
            exists = catagoryService.isPresent(request.form['name'])

            if exists:
                flash('This Catagory already exists. Duplicate entries are are not allowed!')
                return redirect(url_for('catagory.showCatalog'))

            else:

                catagory = Catagory(name=request.form['name'],
                          user_id=user.id)
                eMS.save(catagory)
                flash('Category Successfully Created!')
                return redirect(url_for('catagory.showCatalog'))

        else:
            return render_template('addCatagory.html',show_welcome="false", isLoggedIn=isLoggedIn())

    else:
        return render_template('addCatagory.html',show_welcome="false", isLoggedIn=isLoggedIn())

# Edit a category 
@catagory_routes.route('/catalog/<path:catagory_name>/edit', methods=['GET', 'POST'])
def editCategory(catagory_name):
    
    catagory = catagoryService.getCatagoryByName(catagory_name)
    # Validate if current user is logged in
    if isLoggedIn():

        user = userService.getUserByNameAndId(login_session['username'],login_session['email'])

        # If user exists and is logged in
        if bool(user) == True:

            # If catagory is not created by current user then do nothing else proceed to `elif`
            if catagory.user_id != user.id :
                flash('You do not have access to edit this item!')
                return redirect(url_for('catagory.showCatalog'))

            elif request.method == 'POST' and bool(request.form['name']):
    	    	catagory.name = request.form['name']
    	    	eMS.save(catagory)
    	    	flash('Category Item Successfully Edited!')
    	    	return redirect(url_for('catagory.showCatalog'))

    # If user not logged in or does not have access to modify template then return editcatagory.html
    return render_template('editcategory.html',
                           catagory_name=catagory_name,show_welcome="false", isLoggedIn=isLoggedIn())

# Delete a category
@catagory_routes.route('/catalog/<path:catagory_name>/delete', methods=['GET', 'POST'])
def removeCategory(catagory_name):
    try:
        # Validate if current user is logged in
        isUserLoggedIn = isLoggedIn()

        # Validate if current user is logged in
        if isUserLoggedIn:
            catagory = catagoryService.getCatagoryByName(catagory_name)
            user = userService.getUserByNameAndId(login_session['username'],login_session['email'])
            # If catagory is not created by current user then do nothing else proceed to `elif`
            if catagory.user_id == user.id:
                eMS.delete(catagory)
                flash('Item Deleted Successfully')
                return redirect(url_for('catagory.showCatalog'))

            else:
                flash('You do not have access to delete this item!' )

        # If user not logged in or does not have access to modify template then render showCatalog
        return redirect(url_for('catagory.showCatalog'))
    except TemplateNotFound:
        abort(404)

# Show Category Items
@catagory_routes.route('/catalog/<path:catagory_name>/items/')
def showCategory(catagory_name):
    catagory = catagoryService.getCatagoryByName(catagory_name)
    catagory_id = catagory.id
    categories = catagoryService.getCatagoriesList()
    items = itemService.getItemsForCatagory(catagory.id)
    count = items.__len__()
    isUserLoggedIn = isLoggedIn()
    if isUserLoggedIn == True:
        userName = login_session['username']
        userImage = login_session['picture']
        show_welcome = 'true'
    else:
        userName = ""
        userImage = ""
        show_welcome='false'

    return render_template('items.html', categories=categories, show_welcome=show_welcome, catagory_name=catagory_name, catagory_id=catagory_id, items=items, count=count, isLoggedIn=isUserLoggedIn, user_name=userName, user_image=userImage)


# to get catagories
@catagory_routes.route('/catagories.json')
def getAllCatagories():
    catagories = catagoryService.getAllCatagories()
    return jsonify(catagories)

routes/item.py
from flask import Blueprint, render_template, abort,request,flash,redirect,jsonify,url_for
from jinja2 import TemplateNotFound
from flask import session as login_session


from database.entityManagerService import EntityManagerService, CatagoryService, ItemService, UserService
from database.database_set_up import User,Item,Catagory

import requests

item_routes = Blueprint('item', __name__,
                        template_folder='templates')


# Services for CRUD operations
eMS = EntityManagerService()
userService = UserService()
catagoryService = CatagoryService()
itemService = ItemService()

def isLoggedIn():
    access_token = login_session.get('access_token')
    if access_token is None:
        return False
    else:
        return True

# Add an item
@item_routes.route('/catalog/<path:catagory_name>/add', methods=['GET','POST'])
def addItem(catagory_name):
	try:
		# Validate if current user is logged in
	    if isLoggedIn():
	        catagory = catagoryService.getCatagoryByName(catagory_name)
	        user = userService.getUserByNameAndId(login_session['username'],login_session['email'])

            # Anyone can add item to acatagory but not edit and delete
            if request.method == 'POST':
                exists = itemService.isPresent(request.form['name'],catagory.id)

                if exists:
                    flash('This item already exists. Duplicate entries are are not allowed!')
                    return redirect(url_for('catagory.showCatalog'))

                else:
                    newItem = Item(name= request.form['name'],
    	               description= request.form['description'],
    	               image_url= request.form['image_url'],
    	               catagory_id=catagory.id,
    	               user_id=user.id)
    	            eMS.save(newItem)
    	            flash('Category Item Successfully Created!')
    	            return redirect(url_for('catagory.showCatalog'))

	    return render_template("addItem.html",catagory_name=catagory_name, isLoggedIn=isLoggedIn())

	except TemplateNotFound:
		abort(404)

# Display a Specific Item
@item_routes.route('/catalog/<path:catagory_name>/<path:item_id>/')
def showItem(catagory_name, item_id):
    item = itemService.getItemById(item_id)
    return render_template('item.html', catagory_name=catagory_name, item=item, show_welcome="false", isLoggedIn=isLoggedIn())


# Edit an item
@item_routes.route('/catalog/<path:catagory_name>/<path:item_name>/edit', methods=['GET', 'POST'])
def editItem(catagory_name, item_name):
    
    # Validate if current user is logged in
    if isLoggedIn():
        catagory = catagoryService.getCatagoryByName(catagory_name)
        item = itemService.getItemByNameAndCatagory(catagory.id, item_name)
        user = userService.getUserByNameAndId(login_session['username'],login_session['email'])
        
        # If catagory is not created by current user then do nothing else proceed
        if item.user_id == user.id and request.method == 'POST':
            item.name = request.form['name']
            item.description = request.form['description']
            item.image_url = request.form['image_url']
            eMS.save(item)
            flash('Category Item Successfully Edited!')
            return redirect(url_for('catagory.showCategory', catagory_name=catagory_name,item_id = item.id))


        elif item.user_id != user.id :
            flash('You do not have access to edit this item! ')
            return redirect(url_for('catagory.showCategory', catagory_name=catagory_name,item_id = item.id))

    return render_template('edititem.html',
                           catagory_name=catagory_name,item=item, isLoggedIn=isLoggedIn())

# Remove Item
@item_routes.route('/catalog/<path:catagory_name>/<path:item_name>/delete', methods=['GET', 'POST'])
def removeItem(catagory_name,item_name):
    
    # Validate if current user is logged in
    if isLoggedIn():
        catagory = catagoryService.getCatagoryByName(catagory_name)
        item = itemService.getItemByNameAndCatagory(catagory.id, item_name)
        user = userService.getUserByNameAndId(login_session['username'],login_session['email'])
        if item.user_id == user.id:
            eMS.delete(item)
            flash('Category Item Successfully Deleted!')
        else:
            flash('You do not have access to delete this item! ')

    return redirect(url_for('catagory.showCategory', catagory_name=catagory_name))
        


# to get items
@item_routes.route('/items.json')
def getAllItems():
    items = itemService.getAllItems()
    return jsonify(items)

templates/addCatagory.html
{% extends "index.html" %} {% block title %} Add New Catagory {% endblock %} {% block content %}
<div class=" col-md-12">
    <!-- Page Content -->
    <div class="row">
        <span class="col-md-12"><h4>Add New Category</h4></span>
    </div>
    <hr>
    <form action="{{url_for('catagory.addCatagory')}}" method="post" class="padding-top-10">
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" maxlength="250" name="name">
        </div>
        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Save</button>
            <a href="{{url_for('catagory.showCatalog')}}">
                <button type="button" class="btn btn-danger">Cancel</button>
            </a>
        </div>
    </form>
</div>
{% endblock %}

templates/addItem.html
{% extends "index.html" %}  {% block title %} Add New Item {% endblock %} {% block content %}
<div class=" col-md-12">
    <!-- Page Content -->
    <div class="row">
        <span class="col-md-12"><h4>Add New Item</h4></span>
    </div>
    <hr>
    <form action="{{url_for('item.addItem',catagory_name=catagory_name)}}" method="post" class="padding-top-10">
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" maxlength="250" name="name">
        </div>
        <div class="form-group">
            <label for="description">Description:</label>
            <textarea name="description" id="description" class="form-control" maxlength="250" cols="30" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="image_url">Picture URL:</label>
            <input type="url" class="form-control" id="image_url" maxlength="250" name="image_url">
        </div>
        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-primary">Save</button>
            <a href="{{url_for('catagory.showCategory', catagory_name=catagory_name)}}">
                <button type="button" class="btn btn-danger">Cancel</button>
            </a>
        </div>
    </form>
    <!-- ./ form -->
    <hr>
</div>
{% endblock %}

templates/catagories.html
{% extends "index.html" %} {% block title %} Catagories {% endblock %} {% block content %}
<div class=" col-md-6 padding-left-20 vertical-rule-right">
    <!-- Page Content -->
</div>
<div class="col-md-6 padding-right-20 pull-right">
</div>
<!-- /.container -->
<!-- /.section -->
<style type="text/css">
</style>
<div class="Container">
    <div class="Content row">
        <div class="Wrapper">
            <div class="LeftContent col-md-6" id="scroll-style">
                <div class="row scroll-style">
                    <span class="col-md-8"><h4>Categories</h4></span> {% if isLoggedIn %}
                    <span class="col-md-4">
                        <a href="{{url_for('catagory.addCatagory')}}" class="pull-right">
                            Add Catagory
                        </a>
                    </span> {% endif %}
                </div>
                <hr> {% for i in categories %}
                <div class="main_heading">
                    <a href="{{url_for('catagory.showCategory', catagory_name = i.name)}}">
                        <div class="row">
                            <span class="col-md-8"><h4>{{ i.name }}</h4></span> {% if isLoggedIn %}
                            <div class="col-md-4 margin-top-7">
                                <a href="{{url_for('catagory.removeCategory',catagory_name = i.name)}}" class="pull-right">
                        Remove
                    </a>
                                <a href="{{url_for('catagory.editCategory',catagory_name = i.name)}}" class="pull-right padding-right-10">
                        Edit
                    </a>
                            </div>
                            {% endif %}
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="RightContent col-md-5" id="scroll-style">
                {% block items %} {% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/editcategory.html
{% extends "index.html" %} {% block title %} Edit {{catagory_name}} {% endblock %} {% block content %}
<h1>Edit {{catagory_name}}</h1>
<form action="{{url_for('catagory.editCategory', catagory_name = catagory_name)}}" method="POST" class="padding-top-10">
    <div class="form-group">
        <label for="name">Catagory Name:</label>
        <input type="text" class="form-control" id="name" maxlength="250" name="name">
    </div>
    <div class="form-group">
        <button type="submit" id="submit" class="btn btn-primary">Save</button>
        <a href="{{url_for('catagory.showCatalog')}}">
            <button type="button" class="btn btn-danger">Cancel</button>
        </a>
    </div>
</form>
<!-- ./ form -->
{% endblock %}

templates/edititem.html
{% extends "index.html" %} {% block title %} Edit {{item.name}} {% endblock %} {% block content %}
<section id="editItem" class="edit_item">
    <div class="section-content container padding-1-5">
        <h1>Edit Item</h1>
        <form action="{{url_for('item.editItem', catagory_name=catagory_name, item_name = item.name)}}" method="post" class="col-md-10 padding-top-10">
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" maxlength="250" name="name" value="{{item.name}}">
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea name="description" id="description" class="form-control" maxlength="250" cols="30" rows="3">{{item.description}}</textarea>
            </div>
            <div class="form-group">
                <label for="current-picture">Picture:</label>
            </div>
            <div class="form-group">
                <img src="{{item.image_url}}" alt="{{item.image_url}}" id="current-picture" class="img-thumbnail">
            </div>
            <div class="form-group">
                <label for="image_url">Picture URL:</label>
                <input type="url" class="form-control" id="image_url" maxlength="250" name="image_url" placeholder="{{item.image_url}}" value="{{item.image_url}}">
            </div>
            <div class="form-group">
                <button type="submit" id="submit" class="btn btn-primary">Save</button>
                <a href="{{url_for('catagory.showCategory', catagory_name=catagory_name)}}">
                    <button type="button" class="btn btn-danger">Cancel</button>
                </a>
            </div>
        </form>
        <!-- ./ form -->
    </div>
</section>
<!-- ./ section -->
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/styles.css')}}">
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="padding-top-15 navbar-brand " href="/">Item Catalog !!</a>
            </div>
            {% if isLoggedIn %}
            <div class="pull-right padding-top-15">
                <a href="{{url_for('gdisconnect')}}" class="sign-in-font">Log Out</a>
            </div>
            {% else %}
            <div class="pull-right padding-top-15">
                <a href="{{url_for('showLogin')}}" class="sign-in-font">Log In</a>
            </div>
            {% endif %}
        </div>
    </div>
    <section id="catalog" class="section">
        <div class="container">
            {% if isLoggedIn %} {% if show_welcome == 'true' %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-8 margin-top-12">
                        <h2>Welcome {{user_name}} !!</h2>
                    </div>
                    {% if user_image %}
                    <div class="col-md-4 ">
                        <img src="{{user_image}}" class="pull-right style-userimage img-circle img-responsive">
                    </div>
                    {% endif %}
                    <!-- /.row -->
                </div>
            </div>
            {% endif %} {% endif %}
             {% if get_flashed_messages() %}
            <div class="alert alert-info">
                {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %} {{ message }} {% endfor %} {% endif %} {% endwith %}
            </div>
            {% endif %}
            <div class="panel panel-default col-md-12">
                <div class="panel-body custom-data-height ">
                    {% block content %} {% endblock %}
                    <!-- /.row -->
                </div>
            </div>
        </div>
        <!-- /.container -->
    </section>
    <!-- ./ section -->
</body>
</html>

templates/item.html
{% extends "index.html" %} {% block title %} {{ item.name }}  {% endblock %} {% block content %}
<div class=" col-md-12">
    <!-- Page Content -->
    <h4 class="item_heading">{{ item.name }} </h4>
    <hr>
    <div class="col-md-4 ">
        <img class="img-responsive img-center pull-right" src="{{ item.image_url }}" alt="{{ item.name }} Image">
    </div>
    <div class="col-md-7 col-md-offset-1">
        <p>{{ item.description }}</p>
    </div>
</div>
{% endblock %}

templates/items.html
{% extends "catagories.html" %} {% block items %}
<!-- Page Content -->
<div class="row">
    <span class="col-md-8"><h4>{{catagory_name}} > Items (<strong>{{count}}</strong>)</h4></span> {% if isLoggedIn %}
    <span class="col-md-4">
            <a href="{{url_for('item.addItem', catagory_name = catagory_name)}}" class="pull-right">
                Add Item
            </a>
        </span> {% endif %}
</div>
<hr> {% for i in items %}
<div class="main_heading">
    <a href="{{url_for('item.showItem',catagory_name=catagory_name, item_id = i.id)}}">
        <div class="row">
            <span class="col-md-8"><h4>{{ i.name }}</h4></span> {% if isLoggedIn %}
            <div class="col-md-4 margin-top-7">
                <a href="{{url_for('item.removeItem',catagory_name = catagory_name,item_name = i.name)}}" class="pull-right">
                        Remove
                    </a>
                <a href="{{url_for('item.editItem',catagory_name = catagory_name,item_name = i.name)}}" class="pull-right padding-right-10">
                        Edit
                    </a>
            </div>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %}
<!-- /.div -->
{% endblock %}

templates/login.html
{% extends "index.html" %} {% block title %} Login {% endblock %} {% block content %}  
<!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
</script>
<script src="//apis.google.com/js/platform.js?onload=start">
</script>
<section id="login" class="section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h4>Login :</h4>
            </div>
        </div>
        <div class="row padding-top-15">
            <div class="container">
                <!--gplus signin-->
                <div id="signInButton">
                    <span class="g-signin" data-scope="openid email" data-clientid="374221928768-55m3bt427ni33tok59dbqj1o8mn3khgj.apps.googleusercontent.com" data-redirecturi="postmessage" data-accesstype="offline" data-cookiepolicy="single_host_origin" data-callback="signInCallback" data-approvalprompt="force">
                  </span>
                </div>
                <div id="result"></div>
                <!--/gplus signin-->
            </div>
        </div>
    </div>
</section>
<script>
function signInCallback(authResult) {
    if (authResult['code']) {
        // Hide the sign-in button now that the user is authorized
        $('#signInButton').attr('style', 'display: none');
        debugger;
        // Send the one-time-use code to the server, if the server responds, write a 'login successful' message to the web page and then redirect back to the main restaurants page
        $.ajax({
            type: 'POST',
            url: '/gconnect?state={{STATE}}',
            processData: false,
            data: authResult['code'],
            contentType: 'application/octet-stream; charset=utf-8',
            success: function(result) {
                debugger;
                // Handle or verify the server response if necessary.
                if (result) {
                    $('#result').html('Login Successful!</br>' + '</br>Redirecting...')
                    setTimeout(function() {
                        window.location.href = "/";
                    }, 1000);

                } else if (authResult['error']) {
                    console.log('There was an error: ' + authResult['error']);
                } else {
                    $('#result').html('Failed to make a server-side call. Check your configuration and console.');
                }
            }

        });
    }
}
</script>
{% endblock %}